### PR TITLE
Test build with git 2.43.4 - test software-layer#885

### PR DESCRIPTION
**Pull request by Neves-P**
Tried addressing @ocaisa's review in https://github.com/EESSI/software-layer/pull/885, this PR aims to test these changes.

### CODE REVIEW

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
Failed with
```
== 2025-01-31 16:13:29,988 filetools.py:1924 INFO Creating directory /cvmfs/software.eessi.io/versions/2023.06/software/inux/x86_64/amd/zen2/software/.locks/_cvmfs_software.eessi.io_versions_2023.06_software_linux_x86_64_amd_zen2_software_git_2.43.5-GCC
core-13.2.0-337b4d400023d22207bcc3c29e9ebab31bf96fc2.lock (parents: True, set_gid: False, sticky: False)
== 2025-01-31 16:13:30,083 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to create directory /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/.locks/_cvmfs_software.eessi.io_versions_2023.06_software_linux_x86_64_amd_zen2_software_git_2.43.5-GCCcore-13.2.0-337b4d400023d22207bcc3c29e9ebab31bf96fc2.lock: [Errno 38] Function not implemented: '/cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/.locks' (at easybuild/tools/filetools.py:1936 in mkdir)
== 2025-01-31 16:13:30,086 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): Failed to create lock /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/.locks/_cvmfs_software.eessi.io_versions_2023.06_software_linux_x86_64_amd_zen2_software_git_2.43.5-GCCcore-13.2.0-337b4d400023d22207bcc3c29e9ebab31bf96fc2.lock: [Errno 38] Function not implemented: /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/software/.locks (at easybuild/tools/filetools.py:1966 in create_lock)
```

Looks like the project directory was not picked up now, adding some debug info

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
I introduced a syntax error that I tried correcting now. One more try...

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
Getting a bit further, now failed with:

```>> Checking for EESSI-extend module...
ESC[32m>> Module for EESSI-extend/2023.06-easybuild found!ESC[0m
>> Loading EESSI-extend/2023.06-easybuild module...
-- Using /tmp/$USER as a temporary working directory for installations, you can
override this by setting the environment variable WORKING_DIR and reloading the
module (e.g., /dev/shm is a common option) 
Lmod has detected the following error: You cannot use EESSI_CVMFS_INSTALL in
combination with any other EESSI_*_INSTALL environment variables 
While processing the following module(s):
    Module fullname                 Module Filename
    ---------------                 ---------------
    EESSI-extend/2023.06-easybuild  /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/EESSI-extend/2023.06-easybuild.lua
```

I'll unset `EESSI_CVMFS_INSTALL` when building for `dev.eessi.io` and try again.

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
Build works! But now I need to tweak the `create_tarball.sh` script:
```
>> Collecting list of files/directories to include in tarball via /tmp/dev.eessi.io/overlay-upper/versions...
>> Creating tarball /eessi_bot_job/eessi-2023.06-software-linux-x86_64-amd-zen2-1738343266.tar.gz from /cvmfs/dev.eessi.io/versions/...
tar: /tmp/tmp.nEiBgwtHBS/files.list.txt: Cannot stat: No such file or directory
```

**Comment by Neves-P** [comment]
> Build works! But now I need to tweak the `create_tarball.sh` script:
> 
> ```
> >> Collecting list of files/directories to include in tarball via /tmp/dev.eessi.io/overlay-upper/versions...
> >> Creating tarball /eessi_bot_job/eessi-2023.06-software-linux-x86_64-amd-zen2-1738343266.tar.gz from /cvmfs/dev.eessi.io/versions/...
> tar: /tmp/tmp.nEiBgwtHBS/files.list.txt: Cannot stat: No such file or directory
> ```

This might not have been the issue... The path was too long with `EESSI-extend`:
```-- Using /tmp/$USER as a temporary working directory for installations, you can
override this by setting the environment variable WORKING_DIR and reloading the
module (e.g., /dev/shm is a common option) 
Configuring for use of EESSI_PROJECT_INSTALL under
/cvmfs/dev.eessi.io/versions/2023.06/example/software/linux/x86_64/amd/zen2 
-- To create installations for EESSI, you _must_ have write permissions to
/cvmfs/dev.eessi.io/versions/2023.06/example/software/linux/x86_64/amd/zen2/versions/2023.06/software/linux/x86_64/amd/zen2 ```

Trying out again

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
The latest builds are failing with:
```
>> Using temporary installation of EasyBuild (in /tmp/tmp.8wWafbeH5K/ebtmp)...
>> Final installation in /cvmfs/software.eessi.io/versions/2023.06/software/linux/x86_64/amd/zen2...
ERROR: Failed to determine Lmod version from option '--version' output: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64/usr/bin/lua5.1: ..._injections/2023.06/software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:157: chunk has too many synt
ax levels
stack traceback:
        [C]: in function 'dofile'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:94: in function 'load_site_specific_hooks'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:197: in main chunk
        [C]: in function 'dofile'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:94: in function 'load_site_specific_hooks'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:197: in main chunk
        [C]: in function 'dofile'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:94: in function 'load_site_specific_hooks'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:197: in main chunk
        [C]: in function 'dofile'
        ...
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:94: in function 'load_site_specific_hooks'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:197: in main chunk
        [C]: in function 'dofile'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:94: in function 'load_site_specific_hooks'
        ...software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua:197: in main chunk
        [C]: in function 'require'
        ...compat/linux/x86_64/usr/share/Lmod/libexec/utils.lua:1101: in function 'initialize_lmod'
        ...3.06/compat/linux/x86_64/usr/share/Lmod/libexec/lmod:361: in function 'main'
        ...3.06/compat/linux/x86_64/usr/share/Lmod/libexec/lmod:585: in main chunk
        [C]: ?

```

I've already tried reverting some of the changes I made before, but that didn't help. I'm going back to square one to the point before I tried using `EESSI-extend` and will take it again from there

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
> New job on instance `dev.eessi.io-bot-mc-azure` for architecture `x86_64-amd-zen2` for repository `dev.eessi.io` in job dir `/project/def-users/SHARED/jobs/2025.02/pr_17/249`
> date 	job status 	comment
> Feb 02 19:40:53 UTC 2025 	submitted 	job id `249` awaits release by job manager
> Feb 02 19:41:13 UTC 2025 	released 	job awaits launch by Slurm scheduler
> Feb 02 19:42:16 UTC 2025 	running 	job `249` is running
> Feb 02 19:43:17 UTC 2025 	finished 	
> 😢 FAILURE _(click triangle for details)_
> 
> _Details_
>     ✅ job output file `slurm-249.out`
>     ✅ no message matching `FATAL: `
>     ❌ found message matching `ERROR: `
>     ✅ no message matching `FAILED: `
>     ✅ no message matching ` required modules missing:`
>     ❌ no message matching `No missing installations`
>     ✅ found message matching `.tar.gz created!`
> _Artefacts_
>         No artefacts were created or found.
> 
> Feb 02 19:43:17 UTC 2025 	test result 	
> 🤷 UNKNOWN _(click triangle for detailed information)_

Same error, which makes me think that something else unrelated is causing this... A problem for tomorrow

**Comment by Neves-P** [comment]
bot: build arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen2

**Comment by Neves-P** [comment]
bot: build arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
bot: build arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
I am pretty sure now that the Lua errors were introduced when I first tried using `$EESSI_SITE_INSTALL` here https://github.com/EESSI/software-layer/pull/885/commits/28c6b7ee0a85471064aac2ca3e9313975c6d5de1, which polluted the `SitePackages.lua` file resulting in an endless recursion. 

This file was being written to `/project/def-users/bot/shared/host-injections/2023.06/software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua` and getting picked up no matter what in all subsequent builds. All credit to @bedroge for piecing it together! :pray:

**Comment by Neves-P** [comment]
bot: build arch:aarch64/neoverse_n1

**Comment by Neves-P** [comment]
bot: build arch:aarch64/neoverse_n1
bot: build arch:x86_64/amd/zen2
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:aarch64/neoverse_n1
bot: build arch:x86_64/amd/zen2
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
Recycling this PR to test build with new approach.

bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
/project/def-users/SHARED/jobs/2025.02/pr_17/328

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
We now fail earlier, before getting to `EESSI_install_software.sh`...
```
Mounting 'software.eessi.io' 'read-only' without fuse-overlayfs.
SINGULARITY_BIND=/project/def-users/SHARED/build-logs,/project/def-users/bot/shared,/tmp/bot/EESSI/eessi.nD3XD2IlgX/var-lib-cvmfs:/var/lib/cvmfs,/tmp/bot/EESSI/eessi.nD3XD2IlgX/var-run-cvmfs:/var/run/cvmfs,/project/def-users/bot/shared/host-injections:/opt/eessi,/tmp/bot/EESSI/eessi.nD3XD2IlgX:/tmp,/tmp/bot/EESSI/eessi.nD3XD2IlgX/var-log:/var/log,/tmp/bot/EESSI/eessi.nD3XD2IlgX/usr-local-cuda:/usr/local/cuda,/tmp/bot/EESSI/eessi.nD3XD2IlgX/repos_cfg/default.local:/etc/cvmfs/default.local,/tmp/bot/EESSI/eessi.nD3XD2IlgX/repos_cfg/eessi.io/eessi.io.pub:/etc/cvmfs/keys/eessi.io/eessi.io.pub,/tmp/bot/EESSI/eessi.nD3XD2IlgX/repos_cfg/eessi.io.conf:/etc/cvmfs/domain.d/eessi.io.conf
Launching container with command (next line):
singularity  run  --fusemount container:cvmfs2 cvmfs-config.cern.ch /cvmfs/cvmfs-config.cern.ch --fusemount container:cvmfs2 dev.eessi.io/example /cvmfs_ro/dev.eessi.io/example --fusemount container:fuse-overlayfs -o lowerdir=/cvmfs_ro/dev.eessi.io/example -o upperdir=/tmp/dev.eessi.io/example/overlay-upper -o workdir=/tmp/dev.eessi.io/example/overlay-work /cvmfs/dev.eessi.io/example --fusemount container:cvmfs2 software.eessi.io /cvmfs/software.eessi.io /tmp/bot/EESSI/eessi.nD3XD2IlgX/ghcr.io_eessi_build_node_debian11.sif /project/60006/SHARED/jobs/2025.02/pr_17/event_a71de2f0-f5ee-11ef-87d8-9974c5e83e89/run_000/linux_x86_64_amd_zen4/dev.eessi.io/software-layer/install_software_layer.sh --build-logs-dir /project/def-users/SHARED/build-logs --shared-fs-path /project/def-users/bot/shared
INFO:    Environment variable SINGULARITY_BIND is set, but APPTAINER_BIND is preferred
INFO:    Environment variable SINGULARITY_HOME is set, but APPTAINER_HOME is preferred
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
INFO:    Environment variable SINGULARITYENV_EESSI_OVERRIDE_GPU_CHECK is set, but APPTAINERENV_EESSI_OVERRIDE_GPU_CHECK is preferred
CernVM-FS: pre-mounted on file descriptor 3
CernVM-FS: pre-mounted on file descriptor 3
CernVM-FS: pre-mounted on file descriptor 3
CernVM-FS: loading Fuse module... EESSI_COMPAT_LAYER_DIR_OVERRIDE: /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64
EESSI_COMPAT_LAYER_DIR_OVERRIDE found. Setting EESSI_COMPAT_LAYER_DIR to /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64
done
Failed to initialize loader socket
cannot load store (null) at /cvmfs_ro/dev.eessi.io/example
fuse-overlayfs: cannot read lower dirs: Transport endpoint is not connected
CernVM-FS: loading Fuse module... done
Running 'export EASYBUILD_ROBOT_PATHS=/project/60006/SHARED/jobs/2025.02/pr_17/event_a71de2f0-f5ee-11ef-87d8-9974c5e83e89/run_000/linux_x86_64_amd_zen4/dev.eessi.io/easyconfigs:; export EESSI_OVERRIDE_GPU_CHECK=1; export EESSI_COMPAT_LAYER_DIR=/cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64; export EESSI_VERSION_OVERRIDE=2023.06; export EESSI_DEV_PROJECT=example; export EESSI_CVMFS_REPO_OVERRIDE=/cvmfs/dev.eessi.io/example; export EESSI_SOFTWARE_SUBDIR_OVERRIDE=x86_64/amd/zen4; export SLURM_JOB_ID=353; /project/60006/SHARED/jobs/2025.02/pr_17/event_a71de2f0-f5ee-11ef-87d8-9974c5e83e89/run_000/linux_x86_64_amd_zen4/dev.eessi.io/software-layer/EESSI-install-software.sh --build-logs-dir /project/def-users/SHARED/build-logs --shared-fs-path /project/def-users/bot/shared' in EESSI (/cvmfs/dev.eessi.io/example) 2023.06 compatibility layer environment...
Entering Gentoo Prefix /cvmfs/software.eessi.io/versions/2023.06/compat/linux/x86_64
>> Determining software subdirectory to use for current build host...
>> Picking up pre-defined $EESSI_SOFTWARE_SUBDIR_OVERRIDE: x86_64/amd/zen4
mkdir: cannot create directory '/cvmfs/dev.eessi.io/example': Transport endpoint is not connected
mkdir: cannot create directory '/cvmfs/dev.eessi.io/example': Transport endpoint is not connected
```

Either we pass different arguments to `eessi_container.sh` when building/making the tarball, or this isn´t going to work. I'm not sure that's a good approach, but solving it is top of the agenda for Monday.

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
bot: build arch:x86_64/amd/zen4

**Comment by Neves-P** [comment]
This now seems to work. 

I think because the prefix is now different ( from `/cvmfs/dev.eessi.io/version/2023.06/example` to `/cvmfs/dev.eessi.io/example/versions/2023.06/` the other already installed version of git are being picked up. I'll open a new PR with different software. Let's give that a try.
